#!/bin/bash
#SBATCH --job-name=get_mean              # Название задачи
#SBATCH --error=get_mean-%j.err          # Файл для вывода ошибок
#SBATCH --output=get_mean-%j.log         # Файл для вывода результатов
#SBATCH --time=20:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=4       # Количество ядер CPU, выделенных для одного процесса
#SBATCH -A proj_1466

module purge
module load Python
source deactivate
source activate retinanet

python -u get_mean.py