model:
  name: "retinanet_supercrop"
  id: "774_2"
  train_type: "main"
  fpn: "CustomPyramidFeaturesAT2_small_newLayer_P2"
  # PyramidFeatures
  # CustomPyramidFeatures
  # CustomPyramidFeaturesAT
  # CustomPyramidFeaturesAT2
  # CustomPyramidFeaturesR2 
  # CustomPyramidFeaturesATR2
  # CustomPyramidFeaturesAT2_newLayer
  # CustomPyramidFeaturesAT2_newLayer_P2
  #  PyramidFeaturesP2
  # CustomPyramidFeaturesAT2_small_newLayer_P2
  custom_resnet: False

  pretrain: True
  weigh_path: '/home/maantonov_1/VKR/weights/retinanet/resize/test/small/574/retinanet_resize_574_h:1312_w:1312_last.pt'
  pretrain_on_ImageNet: False
  freeze_backbone: False
  freeze_fpn: False

training:
  batch_size: 3
  num_epochs: 100
  learning_rate: 0.0001
  num_steps: 20
  gamma_coef: 0.5
  size: 1312

  oan_g: 2
  oan_a: 0.05
  bb_pad: 0.5
  criterion: aploss #aploss, focal

  rotate: True

data:
  train_path: '/home/maantonov_1/VKR/data/main_data/train/'
  train_annot_path: 'train_only_pos_annot/annot.json' #'more_sum_more_small_less_empty_train_annot/annot.json' #more_sum_more_small_less_empty_train_annot  more_sum_train_annot

  valid_path: '/home/maantonov_1/VKR/data/main_data/test/'
  valid_annot_path: 'true_annotations/annot.json'

  # valid_path: '/home/maantonov_1/VKR/data/main_data/train/'
  # valid_annot_path: 'val_annot/annot.json'


  double_dataset: True

  double_train_path: '/home/maantonov_1/VKR/data/small_train/train/'
  double_train_annot_path: 'train_annot/annot.json'

  double_valid_path: '/home/maantonov_1/VKR/data/small_train/train/'
  double_valid_annot_path: 'val_annot/annot.json'
  


