model:
  name: "retinanet_super_small"
  id: "108"
  train_type: "main"
  fpn: "CustomPyramidFeatures"
  # PyramidFeatures
  # CustomPyramidFeatures
  # CustomPyramidFeaturesAT
  # CustomPyramidFeaturesAT2
  # CustomPyramidFeaturesR2 
  # CustomPyramidFeaturesATR2
  # CustomPyramidFeaturesAT2_newLayer
  # CustomPyramidFeaturesAT2_newLayer_P2
  #  PyramidFeaturesP2
  # CustomPyramidFeaturesAT2_small_newLayer_P2
  # CustomPyramidFeaturesAT2_small2_newLayer_P2
   # CustomPyramidFeaturesAT_newlayer
  custom_resnet: False

  pretrain: False
  weigh_path: '/home/maantonov_1/VKR/weights/retinanet/test/main/104/retinanet_oan_104.pt'
  pretrain_on_ImageNet: True
  freeze_backbone: False
  freeze_fpn: False



training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.0003
  num_steps: 20
  gamma_coef: 0.5
  size: 640

  oan_g: 2
  oan_a: 0.25
  bb_pad: 0.5
  criterion: focal #aploss, focal

  rotate: True

data:
  train_path: '/home/maantonov_1/VKR/data/main_data/crop_train/'
  train_annot_path: 'only_pos_annot/annot.json'

  valid_path: '/home/maantonov_1/VKR/data/main_data/crop_val/'
  valid_annot_path: 'annotations/annot.json'

# '/home/maantonov_1/VKR/data/crope_data/small/small_crop_train'
# '/home/maantonov_1/VKR/data/crope_data/small/small_crop_val'

# '/home/maantonov_1/VKR/data/crope_data/main/crop_train_1024/'
# '/home/maantonov_1/VKR/data/crope_data/main/crop_val_1024/'

# '/home/maantonov_1/VKR/data/main_data/crop_train/'
# 'only_pos_annot/annot.json'
# '/home/maantonov_1/VKR/data/main_data/crop_val/'

