model:
  name: "retinanet_supercrop"
  id: "565"
  train_type: "small"
  fpn: "CustomPyramidFeaturesAT2_newLayer_P2"
  # PyramidFeatures
  # CustomPyramidFeatures
  # CustomPyramidFeaturesAT
  # CustomPyramidFeaturesAT2
  # CustomPyramidFeaturesR2 
  # CustomPyramidFeaturesATR2
  # CustomPyramidFeaturesAT2_newLayer
  # CustomPyramidFeaturesAT2_newLayer_P2

training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  num_steps: 20
  gamma_coef: 0.5
  size: 1024

  oan_g: 2
  oan_a: 0.05
  bb_pad: 0.0
  criterion: aploss #aploss, focal

data:
  train_path: '/home/maantonov_1/VKR/data/small_train/train/'
  train_annot_path: 'train_annot/annot.json'

  valid_path: '/home/maantonov_1/VKR/data/small_train/train/'
  valid_annot_path: 'val_annot/annot.json'
  


