model:
  name: "retinanet_supercrop"
  id: "1011"
  train_type: "main"
  fpn: "CustomPyramidFeaturesAT2_P2"
  # PyramidFeatures
  # CustomPyramidFeatures
  # CustomPyramidFeaturesAT
  # CustomPyramidFeaturesAT2
  # CustomPyramidFeaturesR2 
  # CustomPyramidFeaturesATR2
  # CustomPyramidFeaturesAT2_newLayer
  # CustomPyramidFeaturesAT2_newLayer_P2
  #  PyramidFeaturesP2
  # CustomPyramidFeaturesAT2_small_newLayer_P2
  # CustomPyramidFeaturesAT_newlayer
  custom_resnet: False

  pretrain: False
  weigh_path: '/home/maantonov_1/VKR/weights/retinanet/resize/test/small/580/retinanet_resize_580_h:1024_w:1024_last.pt' #'/home/maantonov_1/VKR/weights/retinanet/resize/test/small/574/retinanet_resize_574_h:1312_w:1312.pt'
  pretrain_on_ImageNet: True
  freeze_backbone: False
  freeze_fpn: False

training:
  batch_size: 6
  num_epochs: 30
  learning_rate: 0.0003
  num_steps: 10
  gamma_coef: 0.5
  size: 1024

  oan_g: 2
  oan_a: 0.01
  bb_pad: 0.0
  criterion: focal #aploss, focal

  rotate: False

data:
  train_path: '/home/maantonov_1/VKR/data/main_data/train/'
  train_annot_path: 'main/train_only_pos_annot/annot.json' #'more_sum_more_small_less_empty_train_annot/annot.json' #more_sum_more_small_less_empty_train_annot  more_sum_train_annot

  # valid_path: '/home/maantonov_1/VKR/data/main_data/test/'
  # valid_annot_path: 'true_annotations/annot.json'

  valid_path: '/home/maantonov_1/VKR/data/main_data/train/'
  valid_annot_path: 'main/val_annot/annot.json'


  double_dataset: False

  double_train_path: '/home/maantonov_1/VKR/data/small_train/train/'
  double_train_annot_path: 'train_annot/annot.json'

  double_valid_path: '/home/maantonov_1/VKR/data/small_train/train/'
  double_valid_annot_path: 'val_annot/annot.json'
  
  


