#!/bin/bash
#SBATCH --job-name=train_detr_dali              # Название задачи
#SBATCH --error=train_detr_dali-%j.err          # Файл для вывода ошибок
#SBATCH --output=train_detr_dali-%j.log         # Файл для вывода результатов
#SBATCH --time=40:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=2       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
#SBATCH -A proj_1513

module purge
module load Python
source deactivate
source activate retinanet

python -u train_detr_dali.py