#!/bin/bash
#SBATCH --job-name=retinanet_val              # Название задачи
#SBATCH --error=retinanet_val-%j.err          # Файл для вывода ошибок
#SBATCH --output=retinanet_val-%j.log         # Файл для вывода результатов
#SBATCH --time=20:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=2       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
#SBATCH -A proj_1466

module purge
module load Python
source deactivate
source activate retinanet

python -u train.py