#!/bin/bash
#SBATCH --job-name=yolov8l             # Название задачи
#SBATCH --error=yolov8l-%j.err          # Файл для вывода ошибок
#SBATCH --output=yolov8l-%j.log         # Файл для вывода результатов
#SBATCH --time=20:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=4       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
#SBATCH -A proj_1466

module purge
module load Python
source deactivate
source activate yolo

python -u train_yolov8l.py