#!/bin/bash
#SBATCH --job-name=test_centers_two_stages              # Название задачи
#SBATCH --error=test_centers_two_stages-%j.err          # Файл для вывода ошибок
#SBATCH --output=test_centers_two_stages-%j.log         # Файл для вывода результатов
#SBATCH --time=20:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=2       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1  
#SBATCH -A proj_1513



module purge
module load Python
source deactivate
source activate retinanet


python -u test_centers_two_stages.py