#!/bin/bash
#SBATCH --job-name=test_Dali              # Название задачи
#SBATCH --error=test_Dali-%j.err          # Файл для вывода ошибок
#SBATCH --output=test_Dali-%j.log         # Файл для вывода результатов
#SBATCH --time=01:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=4       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
#SBATCH -A proj_1466

module purge
module load Python
source deactivate
source activate retinanet

python -u Dali.py