#!/bin/bash
#SBATCH --job-name=train_retinanet_oan_finetune_on_small_and_main              # Название задачи
#SBATCH --error=train_retinanet_oan_finetune_on_small_and_main-%j.err          # Файл для вывода ошибок
#SBATCH --output=train_retinanet_oan_finetune_on_small_and_main-%j.log         # Файл для вывода результатов
#SBATCH --time=40:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=4       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
#SBATCH -A proj_1466

module purge
module load Python
source deactivate
source activate retinanet

python -u train_retina_oan_finetune.py