#!/bin/bash
#SBATCH --job-name=test_retina_two_stages              # Название задачи
#SBATCH --error=test_retina_two_stages-%j.err          # Файл для вывода ошибок
#SBATCH --output=test_retina_two_stages-%j.log         # Файл для вывода результатов
#SBATCH --time=01:00:00              # Максимальное время выполнения
#SBATCH --ntasks=1                   # Количество MPI процессов
#SBATCH --nodes=1                    # Требуемое кол-во узлов
#SBATCH --cpus-per-task=1       # Количество ядер CPU, выделенных для одного процесса
#SBATCH --gpus 1                     # Требуемое кол-во GPU
# --constraint="type_e"
#SBATCH -A proj_1513

module purge
module load Python
source deactivate
source activate retinanet

python -u test_retina_two_stages.py