model:
  name: "center_supercrop"
  id: "211"
  train_type: "small"
  pretrain_on_ImageNet: True
  model_type: '1'  #1,2


training:
  batch_size: 2
  num_epochs: 100
  learning_rate: 0.0001
  num_steps: 30
  gamma_coef: 0.5
  size: 1920

  oan_g: 2
  oan_a: 0.05
  bb_pad: 0.0
  random_bb_pad: False
  criterion: focal #aploss, focal

data:
  train_path: '/home/maantonov_1/VKR/data/main_data/train/'
  train_annot_path: 'main/new_full_annot/only_pos_annot.json'

  valid_path: '/home/maantonov_1/VKR/data/small_train/train/'
  valid_annot_path: 'val_annot/annot.json'
  


